# Generated by Django 3.0.8 on 2020-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('document_content', models.BinaryField(max_length=100000)),
                ('document_sha1', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
