# Generated by Django 3.0.8 on 2020-08-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitizedInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(verbose_name='date when status was changed')),
                ('document_sha1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.InvoiceDocument')),
            ],
        ),
    ]
