# Generated by Django 3.0.8 on 2020-08-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_digitizedinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitizedinvoice',
            name='status',
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
